version: '3.9'

services:
  database:
    image: postgres
    container_name: postgres_default
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_docker

  redis:
    image: redis
    command: redis-server --requirepass admin
    ports:
      - 6379:6379
